"""empty message

Revision ID: dad07d4523
Revises: c624c74e9b
Create Date: 2017-04-24 23:49:33.228866

"""

# revision identifiers, used by Alembic.
revision = 'dad07d4523'
down_revision = 'c624c74e9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
